version: '3.8'

services:
  ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-app-container
    ports:
      - "8501:8501"
    tty: true
    volumes:
      - "./scripts:/home/data-viz/scripts"