version: '3.8'

services:
  ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "streamlit run scripts/app.py"
    container_name: ai-prompt-data-viz
    ports:
      - "8501:8501"
    tty: true
    volumes:
      - "./scripts:/home/data-viz/scripts"
